version: '3.8'

services:
  reptracker:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_CONVEX_URL=${NEXT_PUBLIC_CONVEX_URL}
        - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
        - NEXT_PUBLIC_VAPI_API_KEY=${NEXT_PUBLIC_VAPI_API_KEY}
        - NEXT_PUBLIC_VAPI_WORKFLOW_ID=${NEXT_PUBLIC_VAPI_WORKFLOW_ID}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped